# version: '3.8'
services:
    # postgres:
    #     image: postgres:16
    #     container_name: postgresdb1
    #     environment:
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=password
    #     volumes:
    #         - postgres-db-volume:/var/lib/postgresql/data
    #     ports:
    #         - 5432:5432
    #     networks:
    #         - postgres-db-network
    # pgadmin:
    #     image: pgadmin41
    #     container_name: repo-pgadmin
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
    #         PGADMIN_DEFAULT_PASSWORD: 'teste'
    #     ports:
    #         - 16543:80
    #     volumes:
    #         - ./servers.json:/pgadmin4/servers.json
    #     networks:
    #         - postgres-db-network

    timescale:
        image: timescale/timescaledb-ha:pg16
        container_name: timescale1
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - /data/timescaledb:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres-db-network
volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data
networks:
    postgres-db-network:
        driver: bridge
